ALTER TABLE "users" DROP COLUMN "username";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "type";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "is_cc";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "nif";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "address";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "address2";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "postal_code";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "postal_code_desc";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "district";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "phone";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "fax";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mobile";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "sale_conditions";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "visits";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "seller";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "financial";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "plafond";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "is_parent";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "parent_client";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "seller_desc";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "seller_email";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "purchases";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "delivery_type";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mandatory_ref";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "shipping_method";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "price_type";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "shipping";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "rgpd";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "rgpd_date";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt_events";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt_services";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt_campaigns";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt_newsletter";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "mkt_surveys";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "active";